### PR TITLE
Include `src/` in published package

### LINKED ISSUE #227: npm package appears to be missing adapters
I can understand how the main build of lawnchair might only include the 'dom' adapter. But I am interested in taking advantage of the async adapters in the order indexeddb,websql,dom in order to get async when it is available (and even on ancient iOS devices) and only use synchronous DOM Storage as a fallback. With npm packages, one could use sub-package requires like `require('lawnchair/src/adapters/indexed-db')` in a file which webpack could slurp up when building my webpack (in the future, I haven’t actually converted my app yet).

The idea is that I could write code like this:

```javascript
'use strict';

const lawnchair = require('lawnchair/src/Lawnchair');
// Register desired adapters
const desiredAdapters = ['indexed-db', 'webkit-sqlite', 'dom'];

// Set Lawnchair on the global object because the adapters require
// that.
window.Lawnchair = lawnchair;

// Unfortunately webpack requires all the requires to be hardcoded.
require('lawnchair/src/adapters/indexed-db');
require('lawnchair/src/adapters/webkit-sqlite');
require('lawnchair/src/adapters/dom');

const thingsStore = new lawnchair({adapter: desiredAdapters, name: 'things'});
```

Could you adjust the published npm package to include `src` so that I can do this?

### PR DESCRIPTION
**Pull request by paolobueno**
Fixes #227

### CODE REVIEW

**Comment by paolobueno** [comment]
ping @brianleroux

**Comment by brianleroux** [comment]
Hey @paolobueno sorry I have not made time for this repo. If you can get the CI passing I'll happily merge/publish!

**Comment by brianleroux** [comment]
Do you want me to publish this on npm?

**Comment by wtrocki** [comment]
@brianleroux - Thank you so much for finding time for responding to all queries!

> Do you want me to publish this on npm?

Yes! If you can publish this will resolve all the issues with the library many people experience. Currently published version is incomplete and all of the issues were already resolved on the master. What we missing is just publish to npm.

**Pull request merged**
